### ISSUE TITLE
My shared albums and My iCloud folders not visible

### ISSUE THREAD

**Issue by crickabhi** [tilltue/TLPhotoPicker#127]
When i go to the drop down menu where the photos and photo albums are listed, and it only lists the albums on my iPhone/iPad. None of my shared albums or iCloud albums are listed or shown.

**Comment by tilltue** [comment]
My Guess is It should work now. I've pushed a fix for this.
version 1.7.1
https://github.com/tilltue/TLPhotoPicker/commit/28472c996a405c452cafbad0d7526a4083d8d34a

**Comment by crickabhi** [comment]
@tilltue still not able to see shared albums, for that i think you need to remove the check at line number 167 in TLPhotoLibrary.swift.

**Comment by tilltue** [comment]
@crickabhi 
https://github.com/tilltue/TLPhotoPicker/issues/54

**Comment by crickabhi** [comment]
@tilltue But i am able to see my shared albums(shown in the shared tab of photos app) on removal of that check.

**Comment by tilltue** [comment]
@crickabhi 
Now, you can used configure options. : allowedAlbumCloudShared
717725f752fbf3121f06dee3f699ac11b3bffd0a
