### ISSUE TITLE
iOS 13 dark mode issue

### ISSUE THREAD

**Issue by danqing** [tilltue/TLPhotoPicker#219]
Thank you for the great library and quick response (as always)!

There seems to be 2 issues with the dark mode implementation:

1. The top tip remains white (minor issue)
2. There's a white strip on the left for like 5-10pt.

I've attached a screenshot here. Would love to get a fix!

![IMG_FC1A650C1785-1](https://user-images.githubusercontent.com/5134133/65366884-936ce500-dc5c-11e9-8208-dd205e992a26.jpeg)

**Comment by tilltue** [comment]
@danqing 
It should work release 2.0.0 I've pushed a fix for this.

**Comment by tilltue** [comment]
I can't published release version. :(
cocoapods issue: https://github.com/CocoaPods/CocoaPods/issues/9176

**Comment by danqing** [comment]
Hmm the top arrow is now black (correct), but the white strip on the left is still present. Is that supposed to be fixed?

**Comment by tilltue** [comment]
@danqing 
Yes!
<img width="476" alt="스크린샷 2019-09-26 오후 12 09 50" src="https://user-images.githubusercontent.com/2108446/65655272-969a1380-e056-11e9-9107-ba3cb3e415cf.png">

**Comment by danqing** [comment]
Hmm I can confirm that the issue is still present on master. (latest Xcode, ios 13 simulator, using your example app)

Looks like sometimes it works fine, but if for example I swipe up and go to a different app and then go back I will still see the white strip.

Lemme know if you can't repro the issue.

<img width="427" alt="Screen Shot 2019-09-26 at 2 02 51 PM" src="https://user-images.githubusercontent.com/5134133/65662261-5e023600-e066-11e9-9124-d1425d84e8ba.png">

**Comment by danqing** [comment]
Oh and I didn't notice it until now, but if you look at the screenshot above, the blue checkmark has a weird background color too.

**Comment by tilltue** [comment]
@danqing 
I've fixed that release 2.0.2 :)
Thanks you!

**Comment by danqing** [comment]
I think the issue is still present. it doesn't appear the first time the pop up is shown, but if you background the app and come back again, you still see the white strip on the left of the popup.
